name: flutter_ejercicios
description: A new Flutter project
publish_to: none 

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - images/logo.png
  uses-material-design: true

flutter_native_splash:
  color: "#ffffff"
  image: images/logo2.png
  color_dark: "#6D6A64"
  image_dark: images/logo2.png

android_12:
  image: images/logo2.png
  icon_background_color: "#ffffff"
  image_dark: images/logo2.png
  icon_background_color_dark: "#121212"

web: false